FORMAT: 1A
HOST: https://localhost:5000/

# Basic ACME Blog API

# Engineering issues [/engineering-issues]

## Get all [GET /engineering-issues]

## Create one [POST /engineering-issues]

## Update one [PUT /engineering-issues/{id}]

## Delete one [DELETE /engineering-issues/{id}]
